### ISSUE TITLE
Add Listing Confirmation Message

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/projects#15]
## URL

https://fraktal-dapp.vercel.app/nft/24/list-item

## Current

After signing listing tx in metamask, there is no confirmation window and page just sits on screenshot. 

## Desired

Pop-up that says "Transaction is confirming".
Once done, has notification and brings user to listing page in marketplace for that listing.

**Screenshot**

![image](https://user-images.githubusercontent.com/43958441/129307288-488340aa-10c3-46c3-ae54-b0e1985e1f19.png)

**Comment by earth2travis** [comment]
Do we have any design inspiration for these messages?

**Comment by earth2travis** [comment]
"Once done, has notification and brings user to listing page in marketplace for that listing."

- Do we want a separate message once the listing is complete?
- What should that message say?
- Do you want to redirect the page to the marketplace?

**Comment by earth2travis** [comment]
Confirming is a view in the middle. Completed is a notification in upper right hand corner

On minting functions it should ask you to add new token to Metamask

**Comment by cryptnotiq** [comment]
Pop-Up: https://www.figma.com/file/lijxplZ91Ue7k1oF8VwjUb/Fraktal?node-id=806%3A4646
Notifications: https://www.figma.com/file/lijxplZ91Ue7k1oF8VwjUb/Fraktal?node-id=801%3A4199
