### ISSUE TITLE
Add Buy Confirmation Message

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/projects#16]
## URL

https://fraktal-dapp.vercel.app/nft/0x0ebdf68ea31cecfd048f819b2a59a7bbe3894b82-0x6/fix-price-sale

## Current

No confirmation screen after signing buy now tx in metamask.

## Desired

Confirmation message that your transaction is processing.

## Screenshot

![image](https://user-images.githubusercontent.com/43958441/129307500-0678daa9-dbfc-4469-bd0e-f55c5546e924.png)

**Comment by earth2travis** [comment]
Do we have any design inspiration for these messages?

**Comment by earth2travis** [comment]
Will there be separate messages for processing and confirmation?
What should each message say?

**Comment by cryptnotiq** [comment]
Pop-Up: https://www.figma.com/file/lijxplZ91Ue7k1oF8VwjUb/Fraktal?node-id=806%3A4646
Notifications: https://www.figma.com/file/lijxplZ91Ue7k1oF8VwjUb/Fraktal?node-id=801%3A4199

**Comment by smombartz** [comment]
I would show show a purchase pending notification in a new section that displays ownership. this section would update when confirmations are complete and would help users see what they own directly from the NFT marketplace page (see #31 for more info)

![image](https://user-images.githubusercontent.com/1377389/134404211-04d20d44-6c10-4761-913a-5d5b27522208.png)
