### ISSUE TITLE
Hover States for all Button

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#32]
## URL
https://fraktal-dapp.vercel.app/

## Current
Not all buttons have hover states. Main menu links do not have any hover states.

## Desired
Ensure that all buttons have a hover state (current behavior is to go from solid black with white text to black outline with black text). Add hover state for top menu links.

## Screenshot
![Hover States](https://user-images.githubusercontent.com/1377389/134407751-eeaacee7-f531-421f-ae72-c75ee23236df.png)

**Comment by daniel-ivanco** [comment]
What should be the result of the hover? Let's say inverted colors as it is for the top-right `View my NFTs` button?

**Comment by smombartz** [comment]
exactly they can go from solid black with white text to black stroke with black text on hover.

regarding menu, I'm adding details to related issue #42
