### ISSUE TITLE
Manage NFT Page Description Breaks Grid

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#33]
## URL
https://fraktal-dapp.vercel.app/nft/19/manage

## Current
Long description text breaks out of grid.

## Desired
Ensure that long description text flows within parent div rather than taking up the whole length of the page.

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/134407652-2ac72452-b99d-47eb-b805-4d69a746d56c.png)

**Comment by daniel-ivanco** [comment]
what is meant by parent div? The width representing the green part on the below screenshot?

![Screenshot 2021-09-24 at 14 42 51](https://user-images.githubusercontent.com/7447229/134675968-603f4c2b-9e49-4c3f-bf6f-e3c3cd0595e8.png)

**Comment by smombartz** [comment]
correct. if you have a wider screen it breaks out even more...

![image](https://user-images.githubusercontent.com/1377389/134715750-d82f1848-f2ef-4ea4-a8d3-a350f708ae13.png)
