### ISSUE TITLE
Manage NFT Deposit Revenue Broken Button Hover

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#34]
## URL
https://fraktal-dapp.vercel.app/nft/19/manage

## Current
Deposit revenue button has hover state that makes it ineligible: white text on white bg

## Desired
Deposit button should have standard button hover (turn from solid with white text to black outline with black text)

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/134407807-6a506af6-78b8-4139-b3c2-f840b76061b1.png)

**Comment by daniel-ivanco** [comment]
the same goes probably for other buttons, like 'Make an Offer' here https://fraktal-dapp.vercel.app/nft/0x080917e141539d50b763ff92f5d54ebcae8d0080-0x11/fix-price-sale
