### ISSUE TITLE
Change Import to Fraktionalize

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/projects#39]
URL: https://fraktal-dapp.vercel.app/my-nfts

Current: Button says import.

Desired Button says "Fraktionalize"

**Comment by daniel-ivanco** [comment]
Is this still valid? The current button says 'Mint NFT', or are we talking about another one?

![Screenshot 2021-09-24 at 14 11 31](https://user-images.githubusercontent.com/7447229/134672072-9d157db1-6346-4904-97da-d7b719f04dca.png)
on

**Comment by smombartz** [comment]
Just seeing this. the updated design still says **Import NFT**. I think **Fractionalize Existing NFT** or **Fractionalize Existing NFT** would be clearer but very long – I still  think Import is the best option (short and clear). thoughts @cryptnotiq?

![image](https://user-images.githubusercontent.com/1377389/139715524-85854c8a-7696-48f0-b675-1aabd627b2e6.png)

**Comment by earth2travis** [comment]
@smombartz if we are fractionalizing all imports I recommend the button say `Fraktionalize`
The final button in the other flow says `List`
