### ISSUE TITLE
Visibility what menu tab is currently selected

### ISSUE THREAD

**Issue by daniel-ivanco** [FraktalNFT/projects#42]
**current state:** 

It is not visible which main menu tab is currently selected

![Screenshot 2021-09-24 at 16 12 01](https://user-images.githubusercontent.com/7447229/134688863-088dd05b-fd6c-4d15-b9af-20d4cdb712be.png)

**desired state:**

Highlight the menu tab which is currently selected. 
We can use for example https://chakra-ui.com/docs/disclosure/tabs

![Screenshot 2021-09-24 at 16 12 53](https://user-images.githubusercontent.com/7447229/134689013-2e3710c4-a5f5-4445-a2a4-df0c079334b9.png)

**Comment by smombartz** [comment]
lets also include hover states. i think more consistent with the design would be something like this:
![image](https://user-images.githubusercontent.com/1377389/134716567-ae82b61d-5d17-46fb-aad3-5d39f4974e01.png)

hover bg is #D3D3D3
