### ISSUE TITLE
NFT Listing Breaks if on Wrong Network

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#43]
currently the whole experience brakes when you're on the wrong network (doesnt display NFT data, forms become unresponsive) which is not a good user experience. instead it would be better if it could display the NFT data and message the user in place that they need to switch the network – even better with a button that prompts metamask to switch networks.

**Wrong Network (Polygon)**
![image](https://user-images.githubusercontent.com/1377389/134435159-40b306e4-292b-4d0e-a124-5c66504bcf3c.png)

**Correct Network (Rinkeby)**
![image](https://user-images.githubusercontent.com/1377389/134435263-693cf248-59b7-4e5e-b71a-2fba7b7f8967.png)

_Originally posted by @smombartz in https://github.com/FraktalNFT/dapp-UI/issues/6#issuecomment-925397340_

**Comment by earth2travis** [comment]
Data is coming from the chain the contract is on

**Comment by earth2travis** [comment]
Can the data still be displayed even if users are on the wrong chain?
