### ISSUE TITLE
Page Title

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#48]
## View Name
All Pages

## Description
* Left align title and move sorting to the right

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/136601870-0650a2a8-a449-4529-8ec5-a962daa83664.png)

## Link to Figma Frame
https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A267

**Comment by DrHongos** [comment]
Corrected in commit 2b1fdff0e98b901fa5c56f2c67452d31073d76e4
Merged in 7b6543a1fcdac052ed200ed6ae012df8ad4c943d
