### ISSUE TITLE
Create Claim Your Sold Fraktions Component

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#53]
## View Name

https://fraktal-dapp.vercel.app/my-nfts

## Description

Component to claim revenue from fractional sales

### Nothing to Claim

![nothing-to-claim](https://user-images.githubusercontent.com/522182/136613141-bb32e244-e2be-4447-9c9f-581e3cf72b73.png)

### Claim All

![claim-all](https://user-images.githubusercontent.com/522182/136613222-624074f0-f9c6-4ff1-8590-1caaf57da5ee.png)

### Nothing to Claim

https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=344%3A3061

### Claim All

https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A529

**Comment by DrHongos** [comment]
We dont keep a list of selled fraktions, instead we can do something like
![image](https://user-images.githubusercontent.com/18542003/139630847-cf78a46a-ce84-4054-a5b2-9d5f6782c6f4.png)
![image](https://user-images.githubusercontent.com/18542003/139631063-d0ea678c-e149-4abd-9deb-7114dcd14577.png)

**Comment by smombartz** [comment]
@DrHongos and team: what you think about this
![image](https://user-images.githubusercontent.com/1377389/139734621-0614952b-eba2-45e9-b344-23b153fd5088.png)

https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-%7C-Raid-Guild?node-id=1309%3A4776
