### ISSUE TITLE
Add Your NFT is Minting Card

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#59]
## View Name

https://fraktal-dapp.vercel.app/my-nfts

## Description

After minting and importing NFTs users should be redirected to `my-nfts` view with a placeholder card until the NFT is loaded

## Screenshot

![minting](https://user-images.githubusercontent.com/522182/136637880-13e54d77-5a1c-4bba-96b4-7d213024ae61.png)

## Link to Figma Frame

[My NFTs Processing](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=1075%3A6309)

**Comment by mackbowes** [comment]
Estimate 1 hour

**Comment by nickcaputo** [comment]
Created context to watch this and image in the grid
<img width="1367" alt="Screen Shot 2021-11-19 at 3 27 33 PM" src="https://user-images.githubusercontent.com/13974846/142703895-5b64ea27-8a99-4a33-98e7-eafc1051f587.png">

**Comment by nickcaputo** [comment]
Created PR at https://github.com/FraktalNFT/dapp-frontend/pull/37
