### ISSUE TITLE
Update Wrong Network Error Message Style

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/projects#6]
**Current**

When metamask is set to a network other than Goerli, the connect button does not work and no error messages are shown.

**Desired**

Button grayed out (unclickable) if on wrong network with Message to switch to correct network (which is currently Goerli but should be Rinkeby once the contracts are redeployed)

Also see #43 – NFT Listing Breaks if on Wrong Network

**Comment by earth2travis** [comment]
Do we have any design inspiration for this view?

![image](https://user-images.githubusercontent.com/522182/129358974-c354ad5b-6830-4413-88dc-8f09f20bb311.png)

**Comment by earth2travis** [comment]
Also see OpenSea or Rarible

**Comment by smombartz** [comment]
currently the whole experience brakes when you're on the wrong network (doesnt display NFT data, forms become unresponsive) which is not a good user experience. instead it would be better if it could display the NFT data and message the user in place that they need to switch the network – even better with a button that prompts metamask to switch networks.

![image](https://user-images.githubusercontent.com/1377389/134434491-409e47b2-3e24-4246-8d1e-7a4463b78c8f.png)

**Comment by earth2travis** [comment]
Set margin auto on the left and right of the error message to keep it aligned with the grid. Update background and text colors.

**Comment by nickcaputo** [comment]
Changed and in PR

**Comment by nickcaputo** [comment]
@earth2travis @DrHongos

**Comment by nickcaputo** [comment]
https://github.com/FraktalNFT/dapp-frontend/pull/29

**Comment by nickcaputo** [comment]
<img width="1037" alt="Screen Shot 2021-11-14 at 11 14 57 AM" src="https://user-images.githubusercontent.com/13974846/141695159-6a6116b0-4ab1-4872-a4fb-f9f710f1010f.png">
