### ISSUE TITLE
NFT Detail Two Column Layout

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#60]
## View Name
NFT Detail

## Description
* Create two column layout for NFT Detail page.
* Left column to hold NFT image and ownership data. Left column is sticky
* Right column to hold all buying and offering functionality, revenue and fraktion holder list

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/137205652-86fec483-e0ed-4767-bff3-98f87068710c.png)

## Link to Figma Frame
https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A413

**Comment by earth2travis** [comment]
So sticky merged to Main
