### ISSUE TITLE
NFT Detail Offers List

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#61]
## View Name
NFT Detail

## Description
* list that shows past and pending offers
* includes: date, address of wallet thats making the offer, offer amount, and action/status (see #62 for actions functionality)

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/137206582-0ccb3873-71cc-4047-81ea-5865f10bce04.png)

## Link to Figma Frame
https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A413

**Comment by mackbowes** [comment]
Blocked by failing subgraph
