### ISSUE TITLE
NFT Detail Offers List Actions

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#62]
## View Name
NFT Details

## Description
* Allow owners of fraktions to accept an offer from the actions list
* Allow owners to reject an accepted offer
* Show offer status as well as how many fraktion holders have accepted in %

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/137206792-2cd5dc47-6013-4b29-b3bf-d4014a366a8e.png)

![image](https://user-images.githubusercontent.com/1377389/137206801-3c12890b-a6a4-4c28-b975-9a8d5000f1da.png)

## Link to Figma Frame
https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A413

**Comment by mackbowes** [comment]
Blocked by failing subgraph

**Comment by mackbowes** [comment]
We tabled this for now - actions are currently 
"Approve Fraktions" (Allows fraktions to be sent to relevant smart contracts automatically)
"Accept" - Locks Fraktions as vote for accepting the buyout
"Cancel" - Unlocks Fraktions as vote for above
and "Claim" - Only viewable if a quorum is reached for buyout AND the user is the offerer
