### ISSUE TITLE
NFT Detail Fraktion Owner List

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#64]
## View Name
NFT Details

## Description
* Show list of fraktion owners addresses and percentage owned

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/137210210-df44ad0a-3761-439f-95f9-61e50ebc6e07.png)

## Link to Figma Frame
https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=343%3A413

**Comment by DrHongos** [comment]
> [FraktalNFT/dapp-frontend@87a4d29](https://github.com/FraktalNFT/dapp-frontend/commit/87a4d29da31288199225f9780c36fdea1ccf7ea1) Nearly done, just blocked on the gql queries because I can't see the schemas

Schemas in:  https://github.com/FraktalNFT/subgraph/blob/main/schema.graphql
for any request of modification pls DM me!
