### ISSUE TITLE
Implement Artists List View

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#69]
## View Name

- Artist List

## Description

This view does not appear to currently be functional. Should allow display and sorting all artists.

### Current

![current-artists](https://user-images.githubusercontent.com/522182/137545404-f7794ef6-649b-4ea6-b6ff-8482701d6df5.png)

### Desired

![desired-artists](https://user-images.githubusercontent.com/522182/137545495-43053550-6ca9-4166-9690-0d1358d3555d.png)

## Link to Figma Frame

- [Artist List](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=393%3A0)

**Comment by mackbowes** [comment]
This is done :)

**Comment by mackbowes** [comment]
...blocked by broken subgraph

**Comment by mackbowes** [comment]
[s](https://github.com/FraktalNFT/dapp-frontend/commit/eee30631ac2ec13bbfbcb2c4a1c18e6dd5420e40)
