### ISSUE TITLE
Missing Confirmation Flow on Minting

### ISSUE THREAD

**Issue by cryptnotiq** [FraktalNFT/projects#7]
**URL**

https://fraktal-dapp.vercel.app/mint-nft

**Current**

After confirming the minting transaction in metamask. The page stays on the data input screen (see screenshot below). 

**Desired**
1. There should be a confirmation pop-up that says "Transaction submitted to the Ethereum blockchain. Please wait a few moments for it to be confirmed." with a button that says 'Continue' and goes to the My Assets Page. 
2. A confirmation notification should appear when the transaction is processed.

**Screenshots**

![image](https://user-images.githubusercontent.com/43958441/129302533-13520af9-dcf8-4279-9a0d-5d03d03608f5.png)

**Comment by earth2travis** [comment]
Do we want to provide the URL to the NFT?

**Comment by earth2travis** [comment]
Do we want to provide a link to the Etherscan transaction?

**Comment by earth2travis** [comment]
Do we have any design inspiration for this view?

**Comment by cryptnotiq** [comment]
Pop-Up: https://www.figma.com/file/lijxplZ91Ue7k1oF8VwjUb/Fraktal?node-id=806%3A4646
Notifications: https://www.figma.com/file/lijxplZ91Ue7k1oF8VwjUb/Fraktal?node-id=801%3A4199
