### ISSUE TITLE
Implement Artists Profile View

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#70]
## View Name

- Artist Profile

## Description

Display NFT collection related to artist

## Screenshot

![desired-artists-profile](https://user-images.githubusercontent.com/522182/137546027-82204f54-2fd9-44f1-b5db-65f50f401d90.png)

## Link to Figma Frame

- [Artist Profile](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-|-Raid-Guild?node-id=393%3A267)

**Comment by mackbowes** [comment]
Tabled Fraktion availability and price display for this pass
