### ISSUE TITLE
Add validation to ensure the caller has enough permission to use transfer from

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#74]
## Issue Number

1

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Missing approval validation

The function `safeTransferFrom()` is defined as public, but is missing the validations required to ensure that the caller has enough permissions. TransferFrom method should ensure that the from address has approved the caller to transfer funds on behalf - which is missing in this function implementation. This will allow any user to call the method directly and withdraw funds.

## Recommendation

Consider adding the validation to ensure the caller has enough permission to use transfer from.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
