### ISSUE TITLE
Use `_beforeTokenTransfer` hook to add validations that apply to all transfers

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#75]
## Issue Number

2

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Batch transfer method can be used to bypass the validation

The function `safeTransferFrom()` uses the input tokenId to perform extra validations. The `ERC1155` standard allows batch transfer methods but the contract does not override the `safeBatchTransferFrom()` to include these validations. This will allow the caller to skip these validations.

## Recommendation

Consider using the `_beforeTokenTransfer` hook to add validations that apply to all transfers.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
