### ISSUE TITLE
Add method to allow the admin to withdraw the fee

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#76]
## Issue Number

3

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Locked funds - fee collected

The function `buy()` collects the fee from the user but there is no way to withdraw the fee in the
contract. This will cause the funds to be locked in the contract forever.

`127| uint256totalPrice=(listing.price*_numberOfShares)+fee;`

Furthermore, the contract allows the buyer to send more funds than required which can never be withdrawn.

## Recommendation

Consider adding a method to allow the admin to withdraw the fee. Return any funds that are not used to the user.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
