### ISSUE TITLE
Fix the parameter order to match the `ECR1155` standard

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#77]
## Issue Number

4

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Non-standard parameter order for function `safeTransferFrom()`

The function `safeTransferFrom()` defines the ‘`to`’ parameter before the ‘`from`’ parameter, which makes it not conform to the `ERC1155` standard.

## Recommendation

Fix the parameter order to match the `ECR1155` standard.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
