### ISSUE TITLE
Replace instances of `transfer()` with `call()`

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#78]
## Issue Number

5

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/FraktalMarket.sol

### Function `withdrawAccruedFees()` can potentially fail when transferring ETH to a smart contract

Function `withdrawAccruedFees()` calls `transfer()` when sending ETH to `_msgSender`, which only forwards 2300 gas. In cases where the `_msgSender` address is a smart contract whose fallback function consumes more than 2300 gas, the call will always fail. This will have the side effect of potentially preventing smart contracts (e.g. DAOs) from receiving transfers.

For a more in-depth discussion of issues with `transfer()` and smart contracts, please refer to https://diligence.consensys.net/blog/2019/09/stop-using-soliditys-transfer-no w/

## Recommendation

Replace instances of `transfer()` with `call()`. Alternatively, `AddressUpgradeable.sendValue()` can also be used instead (this is already being used correctly in `PaymentSplitterUpgradeable.release())`.

### Note 1

In case the chosen fix is replacing `transfer()` with `call()`, make sure that `rescueEth()` is not vulnerable to reentrancy attacks (as it currently would be).

### Note 2

The same issue also exists in the following functions: `FraktalMarket.rescueEth()`, `FraktalMarket.makeOffer()`, `FraktalNFT.createRevenuePayment()` and `Contract.rescueEth()`.

**Comment by mackbowes** [comment]
https://github.com/FraktalNFT/contracts/pull/4

Went with the AddressUpgradeable.sendValue() utility function as it's safer than exposing a .call
