### ISSUE TITLE
Require that `msg.value >= totalPrice`

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#79]
## Issue Number

6

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Function `buy()` will fail if the user sends the exact `totalPrice` amount

Function `buy()` requires that the sent ETH be greater than `totalPrice`, instead of greater than or equal to.

## Recommendation

Require that `msg.value >= totalPrice`.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
