### ISSUE TITLE
Set an upper limit for `_newFee` that does not exceed 100%

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#81]
## Issue Number

8

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/FraktalMarket.sol

### Function `setFee()` does not enforce an upper limit for `_newFee`

Since `fee` is a percentile amount, it would make sense for the newly set `_newFee` to have an upper limit that does not exceed 100%.

## Recommendation

Set an upper limit for `_newFee` that does not exceed 100%.

**Comment by mackbowes** [comment]
https://github.com/FraktalNFT/contracts/pull/5

**Comment by earth2travis** [comment]
Math works
