### ISSUE TITLE
Use different approach to retrieve the caller account

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#83]
## Issue Number

10

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Avoid using `tx.origin`

The contract uses `tx.origin` in several places to retrieve the caller address. This approach usually comes with it’s own risks. An attacker can scam the user to call this method through a proxy.

## Recommendation

Consider using a different approach to retrieve the caller account. For example, the user address can be sent as a parameter value after restricting the function call to a limited set of callers.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
