### ISSUE TITLE
Replace `msg.sender` with `_msgSender()`

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#84]
## Issue Number

11

## File

https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol

### Function `rescueEth()` inconsistently uses both `_msgSender()` and `msg.sender`

Function `rescueEth()` inconsistently mixes and matches between `_msgSender()` and `msg.sender`. This can potentially create vulnerabilities if `_msgSender()` gets overridden later on and the two values are not identical anymore (e.g. if a gas network is paying for the transaction fees).

## Recommendation

Consider replacing `msg.sender` with `_msgSender()`.

**Comment by DrHongos** [comment]
Contract incorrectly audited.
