### ISSUE TITLE
Choose a single compiler version

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#87]
## Issue Number

14

### Wide Solidity compiler target

The contracts use different compiler versions defined by pragmas. It is considered best practice to stick to a single compiler version throughout the codebase.

## Recommendation

Choose a single compiler version.

**Comment by mackbowes** [comment]
https://github.com/FraktalNFT/contracts/pull/2

**Comment by earth2travis** [comment]
Solidity pragma > 0.8.0
License MIT
