### ISSUE TITLE
Complete Miscellaneous Updates

### ISSUE THREAD

**Issue by earth2travis** [FraktalNFT/projects#88]
## Files

- https://github.com/FraktalNFT/contracts/blob/main/contracts/Fraktal1155.sol
- https://github.com/FraktalNFT/contracts/blob/main/contracts/FraktalMarket.sol

### Fraktal1155.sol

- The contract named `Contract` shadows a reserved word. Consider renaming the contract.
- `uint256` is always greater than or equal to 0. Any require statements checks this are invalid and can be removed.

### FraktalMarket.sol

- `>=0` check in function `setFee()` is redundant since `uint16` is never negative.

**Comment by mackbowes** [comment]
https://github.com/FraktalNFT/contracts/pull/2
