### ISSUE TITLE
Mint NFT

### ISSUE THREAD

**Issue by smombartz** [FraktalNFT/projects#89]
## View Name
List NFT (Mint NFT)

## Description
- The default view for the List NFT page
- Left side shows preview of NFT data which user enters on the right
- Right column includes form for Name, Image File, Description, List, Price and Quantity
  - List item allows user to mint and list item on the marketplace. if unselected the item should not show up on the marketplace
  - Price is the price of one fraktion
  - Quantity is the quantity listed for sale out of the 10,000 existing fraktions
- CTA Buttons
  - Buttons are there to help the user through the minting flow. Buttons are inactive until form is filled, then the first button (Mint) becomes active (black) – metamask opens, once approved user goes to the next step.
  - Possible in between step: make Mint button green and fade in and out (50% <> 25% opoacity) and message user that minting is in progress.

## Screenshot
![image](https://user-images.githubusercontent.com/1377389/139717160-362e200f-a5be-4346-bf56-3e6862e247c0.png)

## Link to Figma Frame
[Prototype](https://www.figma.com/proto/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-%7C-Raid-Guild?page-id=341%3A0&node-id=344%3A3456&viewport=292%2C48%2C0.38&scaling=min-zoom&starting-point-node-id=343%3A267)
[Design](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-%7C-Raid-Guild?node-id=1075%3A5194)

**Comment by earth2travis** [comment]
Status text should say, "Your token is minting. This could take several minutes."

**Comment by smombartz** [comment]
quick update and clarification on the button and process states

![image](https://user-images.githubusercontent.com/1377389/140948036-1f04b4ef-b8bf-4f71-aebe-197a504d814b.png)

[Figma](https://www.figma.com/file/n7fGvM4lFZuUsUcOcOXlBc/Fraktal-App-%7C-Raid-Guild?node-id=1533%3A5587)
